### ISSUE TITLE
Uncaught TypeError: 'QVariant' object is not subscriptable


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [Amphibitus/selectThemes#2]
Impossibile caricare il plugin 'selectThemes' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "G:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\selectThemes\__init__.py", line 37, in classFactory
    return selectThemes(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\selectThemes\selectThemes.py", line 52, in __init__
    self.locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

```
selectThemes 3.0.1, QGIS 3.30.0-'s-Hertogenbosch on Windows 10

**Comment by AlisterH** [comment]
The offending line of code should be replaced by this:
```
self.locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]

**Comment by AlisterH** [comment]
Which itself probably requires:
```
from qgis.PyQt.QtCore import QLocale
from qgis.core import QgsSettings
